---
- name: restart-caddy
  become: true
  ansible.builtin.systemd:
    name: caddy
    state: restarted

- name: enable-caddy
  become: true
  ansible.builtin.systemd:
    name: caddy
    enabled: yes