---
# hosts: frontend_host
# become: yes
- name: update apt cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: install caddy
  become: yes
  ansible.builtin.package:
    name: caddy
    state: latest

- name: ensure caddy user exists
  ansible.builtin.user:
    name: caddy
    state: present

- name: ensure caddy group exists
  ansible.builtin.group:
    name: caddy
    state: present

- name: create webserver directory
  become: yes
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    mode: '0755'
    owner: caddy
    group: caddy

- name: copy index.html to directory
  become: yes
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: caddy
    group: caddy
    mode: '0624'

- name: copy client.js to directory
  become: yes
  ansible.builtin.copy:
    src: client.js
    dest: /var/www/html/client.js
    owner: caddy
    group: caddy
    mode: '0624'

- name: configure web client using config
  become: yes
  ansible.builtin.template:
    src: config.js.j2
    dest: /var/www/html/config.js
    owner: caddy
    group: caddy
    mode: '0624'

- name: configure caddy using caddyfile.j2 template
  become: yes
  ansible.builtin.debug:
    var: hostvars

- name: configure caddy using caddyfile.j2 template
  become: yes
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: caddy
    mode: '0644'
  notify: 
    - restart-caddy 
    - enable-caddy